name: check

on:
  schedule:
    - cron: '2-57/5 * * * *'
  workflow_dispatch:

concurrency:
  group: check
  cancel-in-progress: true

jobs:
  run:
    if: vars.ENABLED != 'false'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - run: python check.py
        env:
          ENABLED: ${{ vars.ENABLED }}
          START_DATE: ${{ vars.START_DATE }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
